#!/bin/bash

docker run -it --rm \
  --user $(id -u):$(id -g) \
  -v /etc/localtime:/etc/localtime:ro \
  -v /etc/passwd:/etc/passwd:ro \
  -v ${HOME}/.ssh:/home/.ssh \
  --name storm \
  zacheryph/storm "$@"
